version: '3.7'
services:
  db:
    image: 'postgres:latest'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    # env_file:
    #   - ./env/postgres.env # you can also define env variables like this.
  web:
    build: ./
    ports:
      - '3000:3000'
    volumes:
      - .:/docker/app # add our local code to dockerfile
    depends_on:
      - db # add all dependant container

  worker:
    build: ./
    command: bundle exec sidekiq
    volumes:
      - .:/docker/app
    depends_on:
      - redis
      - db

  redis:
    image: redis:latest

volumes:
  postgres: # named volume
